name: Build Linux Kernel APK for Alpine

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
      - name: Install required Alpine packages
        run: |
          apk update
          apk add --no-cache build-base elfutils-dev openssl-dev bc flex bison perl linux-headers zstd-dev tar git sudo abuild curl

          # 创建 builder 用户
          adduser -D builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          mkdir -p /home/builder/packages
          chown -R builder /home/builder

      - name: Set up abuild
        run: |
          su builder -c 'abuild-keygen -a -n'  # 生成 key
          echo 'PACKAGER_PRIVKEY="/home/builder/.abuild/*.rsa"' >> /etc/abuild.conf

      - name: Prepare kernel source and APKBUILD
        run: |
          su builder -c '
            cd /home/builder
            git clone --depth=1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git linux-6.14
            curl -Lo linux-6.14/config https://raw.githubusercontent.com/huifujing/amd-kernel-6.14.0/main/config-6.1.0-32-amd64

            cat <<EOF > /home/builder/linux-6.14/APKBUILD
# Contributor: You <your@email.com>
pkgname=linux-custom
pkgver=6.14.0
pkgrel=0
pkgdesc="Custom Linux Kernel"
url="https://kernel.org"
arch="x86_64"
license="GPL-2.0-only"
depends=""
makedepends="bash bc openssl-dev perl ncurses-dev elfutils-dev"
source="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-\$pkgver.tar.xz
        config"

build() {
  cd "\$srcdir/linux-\$pkgver"
  cp "\$srcdir/config" .config
  make olddefconfig
  make -j\$(nproc)
}

package() {
  cd "\$srcdir/linux-\$pkgver"
  install -Dm644 arch/x86/boot/bzImage "\$pkgdir"/boot/vmlinuz-\$pkgver
}

sha512sums="SKIP"
EOF
          '

      - name: Build kernel package (.apk)
        run: |
          su builder -c '
            cd /home/builder/linux-6.14
            abuild -r
          '

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-apk
          path: /home/builder/packages/**/linux-custom-*.apk
          retention-days: 7

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: linux-apk-${{ github.run_id }}
          name: Linux Kernel APK Build ${{ github.run_id }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            /home/builder/packages/**/linux-custom-*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
