name: Build Linux Kernel APK for Alpine

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Install required Alpine packages
        run: |
          apk update
          apk add build-base elfutils-dev openssl-dev bc flex bison perl linux-headers zstd-dev tar
          adduser -D builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder /github/workspace

      - name: Set up abuild
        run: |
          su builder -c 'abuild-keygen -a -n'  # 生成签名 key，不交互
          echo "PACKAGER_PRIVKEY=/home/builder/.abuild/*.rsa" >> /etc/abuild.conf

      - name: Prepare kernel source
        run: |
          mkdir -p /home/builder/packages
          cd /home/builder
          git clone --depth=1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git linux-6.14
          cp linux-6.14/Makefile .  # 确保目录结构OK

      - name: Setup APKBUILD and config
        run: |
          cd /home/builder
          mkdir -p linux-6.14
          curl -Lo config https://raw.githubusercontent.com/huifujing/amd-kernel-6.14.0/main/config-6.1.0-32-amd64
          cat > APKBUILD <<'EOF'
          # Contributor: You <your@email.com>
          pkgname=linux-custom
          pkgver=6.14.0
          pkgrel=0
          pkgdesc="Custom Linux Kernel"
          url="https://kernel.org"
          arch="x86_64"
          license="GPL-2.0-only"
          depends=""
          makedepends="bash bc openssl-dev perl ncurses-dev libelf-dev elfutils-dev"
          source="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$pkgver.tar.xz
                  config"

          build() {
            cd "$srcdir/linux-$pkgver"
            cp "$srcdir/config" .config
            make olddefconfig
            make -j$(nproc)
          }

          package() {
            cd "$srcdir/linux-$pkgver"
            install -Dm644 arch/x86/boot/bzImage "$pkgdir"/boot/vmlinuz-$pkgver
          }

          sha512sums="SKIP"
          EOF

      - name: Build kernel package (.apk)
        run: |
          cd /home/builder
          chown -R builder .
          su builder -c 'abuild -r'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-apk
          path: /home/builder/packages/**/linux-custom-*.apk
          retention-days: 7

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: linux-apk-${{ github.run_id }}
          name: Linux Kernel APK Build ${{ github.run_id }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            /home/builder/packages/**/linux-custom-*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
